/*
Author: Ali Taher

Problem:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Algorithm:
Loop through 1-> 4 million and generate Fibonacci sequence and checking if the terms are even, if so add to sum.

*/


#include <iostream>
using namespace std;

int main(){
	int first = 1;
	int second = 2;
	int sum = 2;
	int temp = 0;
	
	while(second < 4000000){
		temp = first + second;
		first = second;
		second = temp;
		if(second % 2 == 0)
			sum += second;		
	}
	
	cout << "Sum "<< sum << endl;
}